app = 'asksandy-server'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = ''
  internal_port = 5000

  [[services.ports]]
    port = 80

  [services.concurrency]
    hard_limit = 50
    soft_limit = 25

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
